### ISSUE TITLE
download dataset 

### ISSUE THREAD

**Issue by Homa2018** [Practical-AI/crnn-pytorch#1]
Hi

I have downloaded dataset from this link "https://ceit.aut.ac.ir/~keyvanrad/download/ML971/project/" , but I can't extract it, I need the password for it.

**Comment by pooya-mohammadi** [comment]
Hi
The password is included in the readme.

**Comment by pooya-mohammadi** [comment]
@Homa2018 
Password: ML971Data

**Comment by Homa2018** [comment]
Thanks for your quick reply.

**Comment by pooya-mohammadi** [comment]
@Homa2018 
You're welcome!
Please start the project and follow me on github for more projects
